### ISSUE TITLE
not run

### ISSUE THREAD

**Issue by xinjijia** [zaher/fbforceexport#2]
![20170612191947](https://user-images.githubusercontent.com/17928411/27031760-2e5a46ea-4fa4-11e7-9cb2-32d5c0267042.jpg)

**Comment by zaher** [comment]
You need minilib from 
https://sourceforge.net/p/minilib/
It is not that blissful program, But I will send u exe

**Comment by zaher** [comment]
There is a exe file in release section, do not forget to make tables.txt file

**Comment by xinjijia** [comment]
Can you give me an exe file?Thank you.

Messages, Warnings: 2, Hints: 50
Note: Duplicate unit "UniDates" in "export", source="C:\Users\Administrator\Desktop\lib\minilib\lib\UniDates.pas"
Note: Duplicate unit "UniDates" in "MiniCommons 1.0.1", ppu="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\lib\units\x86_64-win64\UniDates.ppu", source="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\lib\UniDates.pas"
Note: Duplicate unit "MsgBox" in "export", source="C:\Users\Administrator\Desktop\lib\minilib\lib\MsgBox.pp"
Note: Duplicate unit "MsgBox" in "MiniCommons 1.0.1", ppu="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\lib\units\x86_64-win64\MsgBox.ppu", source="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\lib\MsgBox.pp"
Note: Duplicate unit "mnUtils" in "export", ppu="C:\Users\Administrator\Desktop\fbforceexport-master\fbforceexport-master\lib\x86_64-win64\mnUtils.ppu", source="C:\Users\Administrator\Desktop\lib\minilib\lib\mnUtils.pas"
Note: Duplicate unit "mnUtils" in "MiniCommons 1.0.1", ppu="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\lib\units\x86_64-win64\mnUtils.ppu", source="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\lib\mnUtils.pas"
Note: Duplicate unit "mnStreams" in "export", ppu="C:\Users\Administrator\Desktop\fbforceexport-master\fbforceexport-master\lib\x86_64-win64\mnStreams.ppu", source="C:\Users\Administrator\Desktop\lib\minilib\lib\mnStreams.pas"
Note: Duplicate unit "mnStreams" in "MiniCommons 1.0.1", ppu="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\lib\units\x86_64-win64\mnStreams.ppu", source="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\lib\mnStreams.pas"
Note: Duplicate unit "mnParams" in "export", source="C:\Users\Administrator\Desktop\lib\minilib\lib\mnParams.pas"
Note: Duplicate unit "mnParams" in "MiniCommons 1.0.1", ppu="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\lib\units\x86_64-win64\mnParams.ppu", source="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\lib\mnParams.pas"
Note: Duplicate unit "mnLogs" in "export", source="C:\Users\Administrator\Desktop\lib\minilib\lib\mnLogs.pas"
Note: Duplicate unit "mnLogs" in "MiniCommons 1.0.1", ppu="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\lib\units\x86_64-win64\mnLogs.ppu", source="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\lib\mnLogs.pas"
Note: Duplicate unit "mnFields" in "export", ppu="C:\Users\Administrator\Desktop\fbforceexport-master\fbforceexport-master\lib\x86_64-win64\mnFields.ppu", source="C:\Users\Administrator\Desktop\lib\minilib\lib\mnFields.pas"
Note: Duplicate unit "mnFields" in "MiniCommons 1.0.1", ppu="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\lib\units\x86_64-win64\mnFields.ppu", source="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\lib\mnFields.pas"
Note: Duplicate unit "mnDrivers" in "export", source="C:\Users\Administrator\Desktop\lib\minilib\lib\mnDrivers.pas"
Note: Duplicate unit "mnDrivers" in "MiniCommons 1.0.1", ppu="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\lib\units\x86_64-win64\mnDrivers.ppu", source="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\lib\mnDrivers.pas"
Note: Duplicate unit "mncSQLUtils" in "export", source="C:\Users\Administrator\Desktop\lib\minilib\connection\src\mncSQLUtils.pas"
Note: Duplicate unit "mncSQLUtils" in "MiniConnections 1.0.1", ppu="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\connection\source\units\x86_64-win64\mncSQLUtils.ppu", source="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\connection\db\mncSQLUtils.pas"
Note: Duplicate unit "mncSQL" in "export", ppu="C:\Users\Administrator\Desktop\fbforceexport-master\fbforceexport-master\lib\x86_64-win64\mncSQL.ppu", source="C:\Users\Administrator\Desktop\lib\minilib\connection\src\mncSQL.pas"
Note: Duplicate unit "mncSQL" in "MiniConnections 1.0.1", ppu="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\connection\source\units\x86_64-win64\mncSQL.ppu", source="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\connection\db\mncSQL.pas"
Note: Duplicate unit "mncSchemas" in "export", ppu="C:\Users\Administrator\Desktop\fbforceexport-master\fbforceexport-master\lib\x86_64-win64\mncSchemas.ppu", source="C:\Users\Administrator\Desktop\lib\minilib\connection\src\mncSchemas.pas"
Note: Duplicate unit "mncSchemas" in "MiniConnections 1.0.1", ppu="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\connection\source\units\x86_64-win64\mncSchemas.ppu", source="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\connection\db\mncSchemas.pas"
Note: Duplicate unit "mncDB" in "export", ppu="C:\Users\Administrator\Desktop\fbforceexport-master\fbforceexport-master\lib\x86_64-win64\mncDB.ppu", source="C:\Users\Administrator\Desktop\lib\minilib\connection\src\mncDB.pas"
Note: Duplicate unit "mncDB" in "MiniConnections 1.0.1", ppu="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\connection\source\units\x86_64-win64\mncDB.ppu", source="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\connection\db\mncDB.pas"
Note: Duplicate unit "mncCSVExchanges" in "export", source="C:\Users\Administrator\Desktop\lib\minilib\connection\src\mncCSVExchanges.pas"
Note: Duplicate unit "mncCSVExchanges" in "MiniConnections 1.0.1", ppu="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\connection\source\units\x86_64-win64\mncCSVExchanges.ppu", source="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\connection\source\mncCSVExchanges.pas"
Note: Duplicate unit "mncCSV" in "export", ppu="C:\Users\Administrator\Desktop\fbforceexport-master\fbforceexport-master\lib\x86_64-win64\mncCSV.ppu", source="C:\Users\Administrator\Desktop\lib\minilib\connection\src\mncCSV.pas"
Note: Duplicate unit "mncCSV" in "MiniConnections 1.0.1", ppu="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\connection\source\units\x86_64-win64\mncCSV.ppu", source="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\connection\source\mncCSV.pas"
Note: Duplicate unit "mncConnections" in "export", ppu="C:\Users\Administrator\Desktop\fbforceexport-master\fbforceexport-master\lib\x86_64-win64\mncConnections.ppu", source="C:\Users\Administrator\Desktop\lib\minilib\connection\src\mncConnections.pas"
Note: Duplicate unit "mncConnections" in "MiniConnections 1.0.1", ppu="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\connection\source\units\x86_64-win64\mncConnections.ppu", source="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\connection\source\mncConnections.pas"
Note: Duplicate unit "mncCommons" in "export", ppu="C:\Users\Administrator\Desktop\fbforceexport-master\fbforceexport-master\lib\x86_64-win64\mncCommons.ppu", source="C:\Users\Administrator\Desktop\lib\minilib\connection\src\mncCommons.pas"
Note: Duplicate unit "mncCommons" in "MiniConnections 1.0.1", ppu="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\connection\source\units\x86_64-win64\mncCommons.ppu", source="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\connection\db\mncCommons.pas"
Note: Duplicate unit "mnBase64" in "export", source="C:\Users\Administrator\Desktop\lib\minilib\lib\mnBase64.pas"
Note: Duplicate unit "mnBase64" in "MiniCommons 1.0.1", ppu="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\lib\units\x86_64-win64\mnBase64.ppu", source="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\lib\mnBase64.pas"
Note: Duplicate unit "MiniConnections" in "export", source="C:\Users\Administrator\Desktop\lib\minilib\connection\src\MiniConnections.pas"
Note: Duplicate unit "MiniConnections" in "MiniConnections 1.0.1", ppu="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\connection\source\units\x86_64-win64\MiniConnections.ppu", source="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\connection\source\MiniConnections.pas"
Note: Duplicate unit "MiniCommons" in "export", source="C:\Users\Administrator\Desktop\lib\minilib\lib\MiniCommons.pas"
Note: Duplicate unit "MiniCommons" in "MiniCommons 1.0.1", ppu="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\lib\units\x86_64-win64\MiniCommons.ppu", source="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\lib\MiniCommons.pas"
Note: Duplicate unit "minibidi" in "export", source="C:\Users\Administrator\Desktop\lib\minilib\lib\minibidi.pas"
Note: Duplicate unit "minibidi" in "MiniCommons 1.0.1", ppu="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\lib\units\x86_64-win64\minibidi.ppu", source="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\lib\minibidi.pas"
Note: Duplicate unit "HejriUtils" in "export", source="C:\Users\Administrator\Desktop\lib\minilib\lib\HejriUtils.pas"
Note: Duplicate unit "HejriUtils" in "MiniCommons 1.0.1", ppu="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\lib\units\x86_64-win64\HejriUtils.ppu", source="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\lib\HejriUtils.pas"
Note: Duplicate unit "HejriDates" in "export", source="C:\Users\Administrator\Desktop\lib\minilib\lib\HejriDates.pas"
Note: Duplicate unit "HejriDates" in "MiniCommons 1.0.1", ppu="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\lib\units\x86_64-win64\HejriDates.ppu", source="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\lib\HejriDates.pas"
Note: Duplicate unit "GPSUtils" in "export", source="C:\Users\Administrator\Desktop\lib\minilib\lib\GPSUtils.pas"
Note: Duplicate unit "GPSUtils" in "MiniCommons 1.0.1", source="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\lib\GPSUtils.pas"
Note: Duplicate unit "GPSThreads" in "export", source="C:\Users\Administrator\Desktop\lib\minilib\lib\GPSThreads.pas"
Note: Duplicate unit "GPSThreads" in "MiniCommons 1.0.1", source="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\lib\GPSThreads.pas"
Note: Duplicate unit "base36" in "export", source="C:\Users\Administrator\Desktop\lib\minilib\lib\base36.pas"
Note: Duplicate unit "base36" in "MiniCommons 1.0.1", source="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\lib\base36.pas"
Warning: Duplicate file "minibidi.inc" in "export", path="C:\Users\Administrator\Desktop\lib\minilib\lib\minibidi.inc"
Warning: Duplicate file "minibidi.inc" in "MiniCommons 1.0.1", path="C:\Users\Administrator\Desktop\minilib\minilib-source-5299d071e3686f6328e460864cac151ce57e0b8a\lib\minibidi.inc"
Compile Project, Target: export.exe: Exit code 1, Errors: 7
MainForm.pas(53,3) Error: Identifier not found "InitEmbedMode"
MainForm.pas(72,14) Error: identifier idents no member "ErrorHandles"
MainForm.pas(83,10) Error: identifier idents no member "HeaderLine"
MainForm.pas(83,24) Error: Identifier not found "hdrNormal"
MainForm.pas(84,10) Error: identifier idents no member "DelimiterChar"
MainForm.pas(166,22) Error: identifier idents no member "Clone"
MainForm.pas(169,21) Error: identifier idents no member "Done"
